from addons.numeric_utils import NumericUtils
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: fortesza
    Package: TestProject.Generated.Tests.Fortesza
    Test: Fortesza Register_local
    Generated by: Michelle Rivero (miichr8@gmail.com)
    Generated on 08/30/2021, 00:13:02
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Q8G7HUK3oeFjlTIwfJnWLnlPPLjzW4CMVUxaQ2p3nKE",
                              project_name="fortesza",
                              job_name="Fortesza Register_local")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Fortesza Register."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://staging.fortesza.com/register"
    PrimerNombre = "Michelle"
    SegundoNombre = "Beatriz"
    PrimerApellido = "Rivero"
    SegundoApellido = "Mendoza"
    NumeroIdentidad = "25-688-25"
    NumeroCelular = "04245999860"
    correo = "micaela25"
    Contrasena = "Michelle.1234"
    PIN = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Type '{PrimerNombre}' in 'Ingrese Nombre - copy'
    ingrese_nombre_copy = driver.find_element(By.CSS_SELECTOR,
                                              "#txt-firstname")
    ingrese_nombre_copy.send_keys(f'{PrimerNombre}')

    # 3. Type '{SegundoNombre}' in 'Ingrese Nombre1 - copy'
    ingrese_nombre1_copy = driver.find_element(By.CSS_SELECTOR,
                                               "#txt-secondname")
    ingrese_nombre1_copy.send_keys(f'{SegundoNombre}')

    # 4. Type '{PrimerApellido}' in 'Ingrese Apellido - copy'
    ingrese_apellido_copy = driver.find_element(By.CSS_SELECTOR,
                                                "#txt-firstsurname")
    ingrese_apellido_copy.send_keys(f'{PrimerApellido}')

    # 5. Type '{SegundoApellido}' in 'Ingrese Apellido1 - copy'
    ingrese_apellido1_copy = driver.find_element(By.CSS_SELECTOR,
                                                 "#txt-secondsurname")
    ingrese_apellido1_copy.send_keys(f'{SegundoApellido}')

    # 6. Select the 'passport' option in 'document_type - copy'
    document_type_copy = driver.find_element(By.XPATH,
                                             "/html/body/app-root/app-register/div[3]/div[2]/div[3]/form/div[3]/div[1]/div/div/select")
    Select(document_type_copy).select_by_value("passport")

    # 7. Type '{NumeroIdentidad}' in 'Ingrese n�mero de identidad'
    ingrese_n_mero_de_identidad = driver.find_element(By.XPATH,
                                                      "/html/body/app-root/app-register/div[3]/div[2]/div[3]/form/div[3]/div[2]/div/div/input")
    ingrese_n_mero_de_identidad.send_keys(f'{NumeroIdentidad}')

    # 8. Type 'Venezuela' in 'Ingrese Nacionalidad - copy'
    ingrese_nacionalidad_copy = driver.find_element(By.CSS_SELECTOR,
                                                    "#txt-nationality")
    ingrese_nacionalidad_copy.send_keys("Venezuela")

    # 9. Type '{NumeroCelular}' in 'Ingrese n�mero de celular'
    ingrese_n_mero_de_celular = driver.find_element(By.CSS_SELECTOR,
                                                    "#txt-phone-number")
    ingrese_n_mero_de_celular.send_keys(f'{NumeroCelular}')

    # 10. Type '{correo}@mailinator.com' in 'Ingrese Correo Electr�nico'
    ingrese_correo_electr_nico = driver.find_element(By.CSS_SELECTOR,
                                                     "#txt-email")
    ingrese_correo_electr_nico.send_keys(f'{correo}@mailinator.com')

    # 11. Type '{Contrasena}' in 'Ingrese Contrase�a'
    ingrese_contrase_a = driver.find_element(By.CSS_SELECTOR,
                                             "#txt-password")
    ingrese_contrase_a.send_keys(f'{Contrasena}')

    # 12. Type '{Contrasena}' in 'Confirme su contrase�a'
    confirme_su_contrase_a = driver.find_element(By.CSS_SELECTOR,
                                                 "#txt-confirm-password")
    confirme_su_contrase_a.send_keys(f'{Contrasena}')

    # 13. Click 'DIV1'
    div1 = driver.find_element(By.XPATH,
                               "//label/div")
    div1.click()

    # 14. Click 'Continuar - copy'
    continuar_copy = driver.find_element(By.XPATH,
                                         "//span[. = 'Continuar']")
    continuar_copy.click()

    # 15. Click 'Registrarme - copy'
    step_settings = StepSettings(timeout=15000)
    with DriverStepSettings(driver, step_settings):
        registrarme_copy = driver.find_element(By.XPATH,
                                               "/html/body/app-root/app-register/div[3]/div[2]/div[3]/form/div[9]/button")
        registrarme_copy.click()

    # 16. Click 'Continuar2'
    continuar2 = driver.find_element(By.CSS_SELECTOR,
                                     "#btn-next-or-confirm")
    continuar2.click()

    # 17. Navigate to 'https://www.mailinator.com/v4/public/inboxes.jsp?to={correo}'
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        driver.get(
            f'https://www.mailinator.com/v4/public/inboxes.jsp?to={correo}')

    # 18. Click 'Activaci�n de cuenta'
    activaci_n_de_cuenta = driver.find_element(By.XPATH,
                                               "//td[. = '\n                    Activaci�n de cuenta\n                ']")
    activaci_n_de_cuenta.click()

    # 19. Get text from 'PIN:'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'html_msg_body']|//*[@name = 'html_msg_body']|/html/body/div/main/div[1]/div/div[3]/div/div[1]/iframe"))
    pin_colon_ = driver.find_element(By.XPATH,
                                     "//p[3]/strong")
    step_output = pin_colon_.get_attribute("value")
    PIN = step_output

    # 20. Remove all non numeric characters from '{PIN}'
    step_output = driver.addons().execute(
        NumericUtils.filterdigits(
            input=f'{PIN}'))
    PIN = step_output

    # 21. Scroll window by ('0','45')
    driver.execute_script("window.scrollBy(0,45)")

    # 22. Scroll window by ('0','100')
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'html_msg_body']|//*[@name = 'html_msg_body']|/html/body/div/main/div[1]/div/div[3]/div/div[1]/iframe"))
    driver.execute_script("window.scrollBy(0,100)")

    # 23. Click 'CONFIRMAR MI CUENTA'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@id = 'html_msg_body']|//*[@name = 'html_msg_body']|/html/body/div/main/div[1]/div/div[3]/div/div[1]/iframe"))
    confirmar_mi_cuenta = driver.find_element(By.XPATH,
                                              "//a[. = 'CONFIRMAR MI CUENTA']")
    confirmar_mi_cuenta.click()

    # 24. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 25. Click 'Continuar2'
    continuar2 = driver.find_element(By.CSS_SELECTOR,
                                     "#btn-next-or-confirm")
    continuar2.click()

    # 26. Type '{PIN}' in 'Ingrese su pin de confirmaci�n'
    ingrese_su_pin_de_confirmaci_n = driver.find_element(By.CSS_SELECTOR,
                                                         "#txt-pin-code")
    ingrese_su_pin_de_confirmaci_n.send_keys(f'{PIN}')

    # 27. Click 'Confirmar'
    confirmar = driver.find_element(By.XPATH,
                                    "//span[. = 'Confirmar']")
    confirmar.click()

    # 28. Type '{correo}@mailinator.com' in 'Ingrese su correo'
    step_settings = StepSettings(timeout=35000,
                                 sleep_time=1000,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        ingrese_su_correo = driver.find_element(By.XPATH,
                                                "/html/body/app-root/app-login/div[2]/div[2]/div[3]/form/div[1]/mat-form-field/div/div[1]/div[3]/input")
        ingrese_su_correo.send_keys(f'{correo}@mailinator.com')

    # 29. Type '{Contrasena}' in 'Ingrese su Contrase�a'
    ingrese_su_contrase_a = driver.find_element(By.CSS_SELECTOR,
                                                "#txt-password")
    ingrese_su_contrase_a.send_keys(f'{Contrasena}')

    # 30. Click 'Iniciar Sesión'
    iniciar_sesi_n = driver.find_element(By.CSS_SELECTOR,
                                         "#btn-sign-in-page")
    iniciar_sesi_n.click()

    # 31. Click 'more_vert'
    more_vert = driver.find_element(By.XPATH,
                                    "//mat-icon[. = 'more_vert']")
    more_vert.click()

    # 32. Click 'Perfil de usuario'
    perfil_de_usuario = driver.find_element(By.XPATH,
                                            "//span[. = 'Perfil de usuario']")
    perfil_de_usuario.click()

    # 33. Click 'edit'
    edit = driver.find_element(By.XPATH,
                               "//div[7]//mat-icon")
    edit.click()

    # 34. Click 'DIV3'
    div3 = driver.find_element(By.XPATH,
                               "/html/body/div[2]/div[2]/div/mat-dialog-container/mat-dialog-content/div/div/form/mat-form-field/div/div[1]/div[3]")
    div3.click()

    # 35. Click 'Femenino'
    femenino = driver.find_element(By.XPATH,
                                   "/html/body/div[2]/div[4]/div/div/div/mat-option[2]/span")
    femenino.click()

    # 36. Click 'Aceptar'
    aceptar = driver.find_element(By.XPATH,
                                  "//span[. = 'Aceptar']")
    aceptar.click()

    # 37. Click 'edit1'
    edit1 = driver.find_element(By.XPATH,
                                "//div[4]//mat-icon")
    edit1.click()

    # 38. Clear 'Tel�fono de contacto' contents
    tel_fono_de_contacto = driver.find_element(By.CSS_SELECTOR,
                                               "#mat-input-0")
    tel_fono_de_contacto.clear()

    # 39. Type '04245118813' in 'Tel�fono de contacto'
    tel_fono_de_contacto = driver.find_element(By.CSS_SELECTOR,
                                               "#mat-input-0")
    tel_fono_de_contacto.send_keys("04245118813")

    # 40. Click 'Aceptar'
    aceptar = driver.find_element(By.XPATH,
                                  "//span[. = 'Aceptar']")
    aceptar.click()

    # 41. Scroll window by ('0','102')
    driver.execute_script("window.scrollBy(0,102)")

    # 42. Click 'edit2'
    edit2 = driver.find_element(By.XPATH,
                                "//div[2]/label//mat-icon[. = 'edit']")
    edit2.click()

    # 43. Type 'Lara' in 'Estado'
    estado = driver.find_element(By.CSS_SELECTOR,
                                 "#mat-input-1")
    estado.send_keys("Lara")

    # 44. Type 'Cabudare' in 'Ciudad'
    ciudad = driver.find_element(By.CSS_SELECTOR,
                                 "#mat-input-2")
    ciudad.send_keys("Cabudare")

    # 45. Type 'Urb. Prados del golf' in 'Distrito'
    distrito = driver.find_element(By.CSS_SELECTOR,
                                   "#mat-input-3")
    distrito.send_keys("Urb. Prados del golf")

    # 46. Type '5-9' in 'Calle'
    calle = driver.find_element(By.CSS_SELECTOR,
                                "#mat-input-4")
    calle.send_keys("5-9")

    # 47. Click 'Aceptar'
    aceptar = driver.find_element(By.XPATH,
                                  "//span[. = 'Aceptar']")
    aceptar.click()

    # 48. Scroll window by ('0','102')
    driver.execute_script("window.scrollBy(0,102)")

    # 49. Click 'edit3'
    edit3 = driver.find_element(By.XPATH,
                                "//div[3]/div[3]//mat-icon[. = 'edit']")
    edit3.click()

    # 50. Type 'Lara' in 'Estado1'
    estado1 = driver.find_element(By.XPATH,
                                  "/html/body/div[2]/div[2]/div/mat-dialog-container/mat-dialog-content/div/div/form/mat-form-field[1]/div/div[1]/div[3]/input")
    estado1.send_keys("Lara")

    # 51. Type 'Barquisimeto' in 'Ciudad1'
    ciudad1 = driver.find_element(By.XPATH,
                                  "/html/body/div[2]/div[2]/div/mat-dialog-container/mat-dialog-content/div/div/form/mat-form-field[2]/div/div[1]/div[3]/input")
    ciudad1.send_keys("Barquisimeto")

    # 52. Click 'Aceptar'
    aceptar = driver.find_element(By.XPATH,
                                  "//span[. = 'Aceptar']")
    aceptar.click()

    # 53. Click 'edit4'
    edit4 = driver.find_element(By.XPATH,
                                "//div[2]/div[3]/label//mat-icon[. = 'edit']")
    edit4.click()

    # 54. Type 'Michelle.12345' in 'Nueva contrase�a'
    nueva_contrase_a = driver.find_element(By.CSS_SELECTOR,
                                           "#mat-input-7")
    nueva_contrase_a.send_keys("Michelle.12345")

    # 55. Type 'Michelle.12345' in 'Confirmar contrase�a'
    confirmar_contrase_a = driver.find_element(By.CSS_SELECTOR,
                                               "#mat-input-8")
    confirmar_contrase_a.send_keys("Michelle.12345")

    # 56. Click 'Aceptar'
    aceptar = driver.find_element(By.XPATH,
                                  "//span[. = 'Aceptar']")
    aceptar.click()

    # 57. Click 'more_vert'
    more_vert = driver.find_element(By.XPATH,
                                    "//mat-icon[. = 'more_vert']")
    more_vert.click()

    # 58. Click 'Cerrar sesi�n'
    cerrar_sesi_n = driver.find_element(By.XPATH,
                                        "//span[. = 'Cerrar sesi�n']")
    cerrar_sesi_n.click()
